### PR TITLE
Speech to text script as a demo

### PR DESCRIPTION
**Pull request by MadSons**

### CODE REVIEW

**Comment by revanthsenthil** [comment]
Delete the .gitkeep in scripts if there is a demo script inside that directory. The `.gitkeep` is a placeholder for github to create an empty directory.

**Review by revanthsenthil — COMMENTED** [review]
As mentioned in the comments, make sure to delete the `.gitkeep` when adding files to directories with just a `.gitkeep`

**Comment by MadSons** [comment]
Ah shoot okay

**Comment by MadSons** [comment]
I'm going to set up my ubuntu system next week. There are many commits here because I cannot check the CI without pushing code

**Comment by MadSons** [comment]
Dependencies fixed

**Review by uchaudhary — APPROVED** [review]

**Review by revanthsenthil — APPROVED** [review]
lgtm!

**Pull request merged**
